# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weightPiece',
            new_name='weight_piece',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='eater',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='ration',
        ),
        migrations.AlterField(
            model_name='eater',
            name='age',
            field=models.IntegerField(default=23, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(110)]),
        ),
        migrations.AlterField(
            model_name='eater',
            name='height',
            field=models.FloatField(default=193, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='eater',
            name='lifestyle',
            field=models.CharField(choices=[('S', 'Sedentary'), ('L', 'Light'), ('A', 'Average')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='eater',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='eater',
            name='weight',
            field=models.FloatField(default=73, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.product'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration', models.CharField(choices=[('BF', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('eater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealentry',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='tracker.meal'),
            preserve_default=False,
        ),
    ]
